club/app/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required
app_name ='app'
urlpatterns = [
    path('profile/', views.profile,name='profile'),
    path('historial/',views.historial,name='historial'),
    path('logout/',views.logout_view,name="logout"),
    path('login/',views.LoginView.as_view(),name="login"),
    #path('alumnos/', views.AlumnosListView.as_view(), name='alumnos'),
    path('paquetes/',views.paquetes,name='paquetes'),
    path('formNotification/',views.notificacionPage,name="form_notification"),
    path('notificationsList/',views.notificationsList,name='notificationsList'),
    path('notificationsList/delete_notification/<int:id>',views.deleteNotification,name="borrar_notificacion"),
    path('notificationsList/vista/<int:id>',views.notificacion,name='notificacion'),
    path('notificationsList/delete_by_topic/<str:verb>',views.deleteByTopicNotifications,name='delete_by_topic'),
    path('notificationsList/delete_all_notifications/',views.deleteAllNotification,name='delete_all'),
    path('paquetes/<uuid:paquete_id>/',views.clases,name='clases'),
    path('paquetes/<uuid:paquete_id>/<uuid:clase_id>',views.clase,name='clase'),
    path('events',login_required(views.Eventos.as_view()),name="events"),
    path('change_password/', views.change_password, name='change_password'),
]

club/blog/urls.py
from django.urls import path
from . import views

app_name ='blog'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('testimony/', views.testimony, name='testimony'),
    path('blog/',views.blog.as_view(),name='blog'),
    path('blog/<uuid:id>/',views.postDetail,name="post_detail"),
    path('contact/', views.contact,name="contact"),
    path('services/', views.services, name='services')

]

club/club/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls

admin.site.site_header = "Club de Tareas"
admin.site.site_title = "Club de Tereas Portal"
admin.site.index_title = "Bienvenido al Club de tareas"

urlpatterns = [
    path('', include('app.urls')),
    path('',include('blog.urls')),
    path('admin/', admin.site.urls),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

club/app/templates/app/base.html
{% load static %}
{% load notifications_tags %}
{% notifications_unread as unread_count %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Club de tareas</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta property="og:url"           content="http://127.0.0.1:8000" />
    <meta property="og:type"          content="website" />
    <meta property="og:title"         content="Club de Tareas" />
    <meta property="og:description"   content="Centro de Tutorias para alumnos" />
    {% block meta_tag %}{% endblock%}
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'app/css/open-iconic-bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'app/css/animate.css'%}">
    <link rel="stylesheet" href="{% static 'app/css/search.css'%}">
    <link rel="stylesheet" href="{% static 'app/css/owl.carousel.min.css'%}">
    <link rel="stylesheet" href="{% static 'app/css/owl.theme.default.min.css'%}">
    <link rel="stylesheet" href="{% static 'app/css/magnific-popup.css'%}">
    <link rel="stylesheet" href="{% static 'app/css/aos.css'%}">
    <link rel="stylesheet" href="{% static 'app/css/ionicons.min.css'%}">
    <link rel="stylesheet" href="{% static 'app/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/fix.css' %}">
    {% block css_tag %}{%endblock%}
  </head>
  <body  data-target=".site-navbar-target" data-offset="300">

  <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light site-navbar-target" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href="index.html">Club de <span>Tareas</span></a>
	      <button class="navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>

	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav nav ml-auto">
	          <li class="nav-item"><a href="{% url 'blog:home' %}" class="nav-link"><span>Home</span></a></li>
	          <li class="nav-item"><a href="{% url 'blog:about' %}"  class="nav-link"><span>Acerca</span></a></li>
	          <li class="nav-item"><a href="{% url 'blog:testimony' %}"  class="nav-link"><span>Testimonios</span></a></li>
	          <li class="nav-item"><a href="{% url 'app:services' %}" class="nav-link"><span>Servicios</span></a></li>
            <li class="nav-item"><a href="{% url 'blog:blog' %}" class="nav-link"><span>Blog</span></a></li>

          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="nav-item"><a href="{% url 'blog:contact' %}" class="nav-link"><span>Contacto</span></a></li>
            {% if request.user.is_authenticated %}

            <div class="dropdown" style="padding-top:5px;padding-right:5px">
                    <a style="border-radius: 10px 10px 10px 10px !important;
                             -moz-border-radius: 10px 10px 10px 10px;
                             -webkit-border-radius: 10px 10px 10px 10px;"
                      class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      {% if unread_count %}
                          <svg viewBox="0 0 8 8"
                               width="8px"
                               height="8px">
                              <circle cx="4"
                                      cy="4"
                                      r="4"
                                      fill="#ff6b6b"
                                      ></circle>
                          </svg>
                      {% endif %}
                        {{ request.user.username }}
                    </a>

                    <div class="dropdown-menu ftco-animate" aria-labelledby="dropdownMenuLink">
                      <a class="dropdown-item" href="{% url 'app:profile' %}"><span>Perfil</span></a>
                      <a class="dropdown-item" href="{% url 'app:paquetes' %}"><span>Paquetes</span></a>
                      <a class="dropdown-item" href="{% url 'app:historial' %}"><span>Historial</span></a>
                      <a class="dropdown-item" href = "{% url 'app:list' %}" >
                        <span>Notificaciones</span>
                          {% if unread_count %}
                          <span class="badge badge-danger">{{ unread_count }}</span>
                          {% endif %}
                      </a>
                      <a class="dropdown-item" href="{% url 'app:logout' %}"><span>Logout</span></a>
                    </div>
              </div>
              <li>
                <div class="inset">
                  <img src="{{ request.user.imagen.url }}">
                </div>
              </li>
            {% else %}
              <li class="nav-item"><a href="{% url 'app:login' %}"  class="nav-link"><span>Login</span></a></li>
            </ul>
          {% endif %}

	      </div>
	    </div>
	  </nav>

    {% block content %}{% endblock %}


    <footer class="ftco-footer ftco-section">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">About DigiLab</h2>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
              <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4 ml-md-4">
              <h2 class="ftco-heading-2">Links</h2>
              <ul class="list-unstyled">
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Home</a></li>
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>About</a></li>
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Services</a></li>
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Projects</a></li>
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Contact</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
             <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Services</h2>
              <ul class="list-unstyled">
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Web Design</a></li>
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Web Development</a></li>
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Business Strategy</a></li>
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Data Analysis</a></li>
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Graphic Design</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
            	<h2 class="ftco-heading-2">Have a Questions?</h2>
            	<div class="block-23 mb-3">
	              <ul>
	                <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
	                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
	                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
	              </ul>
	            </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
        Icons made by <a href="https://www.flaticon.com/authors/those-icons" title="Those Icons">Those Icons</a> from <a href="https://www.flaticon.com/" title="Flaticon"> www.flaticon.com</a>
          </div>
        </div>
      </div>
    </footer>



  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>

  <div id="fb-root"></div>
  <script src="{% static 'app/js/jquery.min.js' %}"></script>
  <script src="{% static 'app/js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'app/js/popper.min.js' %}"></script>
  <script src="{% static 'app/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'app/js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'app/js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'app/js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'app/js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'app/js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'app/js/aos.js'%}"></script>
  <script src="{% static 'app/js/jquery.animateNumber.min.js' %}"></script>
  <script src="{% static 'app/js/scrollax.min.js' %}"></script>
  <!-- <script src="{% static 'app/js/google-map.js' %}"></script> -->
  <script src="{% static 'app/js/main.js' %}"></script>
    {% block script_tag %}{% endblock%}

  <!--<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>-->
  <script async defer crossorigin="anonymous" src="https://connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v5.0"></script>

  </body>
</html>

club/app/templates/app/change_password.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
<section class="ftco-section"  style="background:#31de79">
  <div class="container">
      <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Guardar Cambios</button>
      </form>
  </div>
</section>
{% endblock content  %}

club/app/templates/app/clases.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}

<section class="ftco-section ftco-project"  style="background:#31de79">
  <div class="container px-md-5">
   <p class="info-alumno ftco-animate titulo_paquetes"  style="text-transform: uppercase; color: #7c795d; font-family: 'Trocchi', serif; font-size: 25px; font-weight: normal; line-height: 48px; margin: 0;padding:10px;text-align:center;">
     Alumno:  {{ student.nombre }} {{ student.apellido }}(Paquete {{ paquete.tipo_de_paquete }})
   </p>
   <p class="info-alumno ftco-animate titulo_paquetes"style="font-size:25px">Horas consumidas: <span style="font-weight: bold">{{ paquete.horas_consumidas}}</span></p>
   <p  class="info-alumno ftco-animate titulo_paquetes" style="font-size:25px">Horas restantes: <span style="font-weight: bold">{{ paquete.horas_restantes}}</span></p>
   <button type="button" style="margin-bottom: 10px;"class="btn btn-info" data-toggle="modal" data-target=".bd-example-modal-lg">Observaciones</button>
   <table class="table table-hover table-sm table-bordered ftco-animate" style="background: white;">
   <!--Table head-->
   <thead>
     <tr>
       <th scope="col">Asignatura</th>
       <th scope="col">Tiempo de Sesión</th>
       <th scope="col">Detalles</th>
     </tr>
   </thead>
   <!--Table head-->
   <!--Table body-->
   <tbody>
     {% for clase in clases %}
      <tr>
        <!--<th scope="row"><i style="font-size: 25px" class="fa fa-user"></i></th>-->
        <td>{{ clase.asignatura }}</td>
        <td>{{ clase.tiempo_de_sesion }} Hrs</td>
        <td><a href="{% url 'app:clase' paquete_id=paquete.id clase_id=clase.id %}"><button type="button" class="btn btn-primary">Mostrar</button></a></td>
      </tr>

     {% endfor %}
   </tbody>
   <!--Table body-->
   </table>

   <div style="height: 40px; width: 100%; position:relative"class="mt-5">
      <a href="{% url 'app:paquetes'%}" style="position: absolute; right:0">

      <button type="button" class="btn btn-primary" style="font-size:15px;">
            <i class="fa fa-chevron-left"></i> Ir Paquetes</button>
      </a>
    </div>

  </div>
</section>
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
        <h5 class="modal-title">Observaciones de las clases</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% for clase in clases %}
           {% if clase.observaciones %}
            <p>{{ clase.observaciones }} | {{ clase.tiempo_de_inicio }}</p>
           {% else %}
             <p> sin observerciones | {{ clase.tiempo_de_inicio }}</p>
          {% endif %}
        {% endfor %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>

		</div>
	</div>
{% endblock content  %}

club/app/templates/app/delete_all_notifications.html
{% extends 'main/base.html' %}
{% block content %}
    <div class="content-section">
        <form method="POST" class="ftco-animate" style="padding-top: 80px;">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Eliminar notificaciones</legend>
                <h4>{{ mensaje }}</h4>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Si, Eliminar</button>
                <a class="btn btn-outline-secondary" href="{% url 'app:notificationsList'%}">Cancelar</a>
            </div>
        </form>
    </div>
{% endblock content %}

club/app/templates/app/delete_by_topic_notifications.html
{% extends 'main/base.html' %}
{% block content %}
    <div class="content-section">
        <form   method="POST" class="ftco-animate" style="padding-top: 80px;">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Eliminar notificaciones</legend>
                <h4>Estas seguro de eliminar todas las notificaciones de {{ verb}}</h4>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Si, Eliminar</button>
                <a class="btn btn-outline-secondary" href="{% url 'app:notificationsList'%}">Cancelar</a>
            </div>
        </form>
    </div>
{% endblock content %}

club/app/templates/app/delete_notification.html
{% extends 'main/base.html' %}
{% block content %}
    <div class="content-section">
        <form method="POST" class="ftco-animate" style="padding-top: 80px;">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Eliminar notificación</legend>
                <h4>Estas seguro de eliminar la notificacion de {{ notificacion.actor.nombre }}</h4>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Si, Eliminar</button>
                <a class="btn btn-outline-secondary" href="{% url 'app:notificationsList'%}">Cancelar</a>
            </div>
        </form>
    </div>
{% endblock content %}

club/app/templates/app/eventos.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
<section class="ftco-section" style="background:#31de79">
  <div class="container" style="background:#31de79">
    <form action="{% url 'app:events' %}" method="get">
        <select name="seleccion" id="drop" style="margin-bottom: 20px;">
                <option  {% if seleccion == 'clases' %} selected="selected" {% endif %} value="clases">Clases</option>
                <option {% if seleccion == 'notificaciones' %} selected="selected" {% endif %} value="notificaciones">Notificaciones</option>
        </select>
        <button type="submit">Buscar</button>
     </form>

    <div id='calendar'   class=ftco-animate></div>
    </div>

</section>
{%endblock%}

{% block  script_tag %}
<script>
    $(document).ready(function() {
   
        $('#calendar').fullCalendar({
          monthNames: ['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
          monthNamesShort: ['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'],
          dayNames: ['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'],
          dayNamesShort: ['Dom','Lun','Mar','Mié','Jue','Vie','Sáb'],
            events: [

                {% for event in eventslist %}
                    {
                        title: '{{ event.titulo }}',
                        start : '{{ event.fecha|date:"Y-m-d" }}',
                        {% if seleccion == "clases" %}
                        url: '/paquetes/{{ event.paquete_id }}/{{ event.clase_id }}',
                        {% else %}
                          url: '/notificationsList/vista/{{ event.id }}',
                        {%endif%}
                        color: '{{ event.color }}'
                    },
                {% endfor %}
            ],

            eventClick: function(event) {
                if (event.url){
                    window.open(event.url, "_blank");
                    return false;
                }
            },

            height: 650,
        });
    });
  </script>
  {%endblock%}

club/app/templates/app/notificationsList.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
  <section class="ftco-section notifications-fix-top" style="background:#31de79">
    <div class="container ftco-animate">
    <div style="background-color: white;position: relative; width:100%; height:100px;">
      <div class="row mt-4 ml-0"  style="position: absolute; left:5%;top:-15px;">
         <button class="btn btn-fix"  style="border-radius: 0;background:#31de79;" role="button">Mensajes de usuarios</button>
       </div>

      <button class="btn btn-primary ml-1 btn-fix" style="position: absolute; right:5px; bottom:10px;">
            <a  style="color: black;border-radius:0;"href="{% url 'app:form_notification'%}">Enviar Notificación</a>
      </button>
      {% if  notificaciones %}
              <a  style="font-size: 40px;position: absolute; right:155px;bottom:-10px;" href="{% url 'app:delete_by_topic' verb='notificacion-de-usuario' %}" class="btn"><i class="fa fa-trash"></i></a>
      {% endif %}
    </div>


    <div class="row mt-2"  style="padding:0">
        <ul class="list-group" style="width: 100%">
            {% if notificaciones %}
                {% for notificacion in notificaciones %}

                 <div class="container" style="padding-bottom: 10px; padding-top: 10px">
                   <div style="background-color: white;border-radius: 5px; position: relative ">
                     <div class="inset">
                       <img  class="img-fix" style="width: 80px;height:80px;padding:5px" src="{{ notificacion.actor.imagen.url }}">
                     </div>
                     {% if notificacion.unread %}
                         <span class="badge badge-success" style="border-radius: 50%; position:absolute; top:10%; left:0;
                         z-index:1000;transform: translate(-50%,-50%);">
                         <i class="fa fa-comments"></i>
                            </span>
                     {%else%}
                         <span class="badge badge-danger" style="border-radius: 50%; position:absolute; top:10%; left:0;
                        z-index: 1000;transform: translate(-50%,-50%);">
                         <i class="fa fa-comments"></i>
                          </span>
                     {%endif%}

                       <div  style="padding-left: 80px;position:relative;">
                         <p> Asunto: {{ notificacion.verb}}</p>
                         <span style="color: #5897fb;">
                           Notificacion de: {{ notificacion.actor.nombre }} {{ notificacion.actor.apellido}}
                         </span>
                        <br>
                         <span>
                                   Fecha: {{ notificacion.timestamp|date:"Y/m/d H:i:s" }}
                         </span>
                         <br>
                        <div  class="content-gap" style="height:50px;width: 100px;">
                            <div style="position:absolute; bottom:0; right:0; padding-bottom: 10px; padding-right: 10px;">
                               <a  style="font-size: 30px;"href="{% url 'app:notificacion'  id=notificacion.id %}" class="btn"><i class="fa fa-file"></i></a>
                              <a  style="font-size: 35px;"href="{% url 'app:borrar_notificacion' id=notificacion.id %}" class="btn"><i class="fa fa-trash"></i></a>
                            </div>
                       </div>

                   </div>
                 </div>
               </div>

                {% endfor %}
            {% else %}
            <ul class="list-group" style="padding-bottom: 20px">
                  <li class="list-group-item">No hay Notificaciones</li>
            </ul>
            {% endif%}
        </ul>

        {% if notificaciones %}

        <nav style="margin-left: 15px;">
          <ul class="pagination">
            {% if notificaciones.has_previous %}
              <li class="page-item">
                <a
                  class="page-link"
                  href="?page={{notificaciones.previous_page_number}}">Anterior</a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="#">Anterior</a>
              </li>
            {% endif %}
            {% for pagenum in notificaciones.paginator.page_range %}
            <li
               class="page-item{% if notificaciones.number == pagenum %} active {% endif %}">
              <a class="page-link" href="?page={{pagenum}}">{{pagenum}}</a>
            </li>
           {% endfor %}
           {% if notificaciones.has_next %}
             <li class="page-item">
              <a class="page-link" href="?page={{notificaciones.next_page_number}}">Siguiente</a>
             </li>
           {% else %}
             <li class="page-item disabled">
               <a class="page-link" href="#">Siguiente</a>
             </li>
           {% endif %}
         </ul>
       </nav>
          {% endif %}

    </div>
  </div>
</div>
</section>


{% endblock content %}

club/app/templates/app/paquetes.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}

<section class="ftco-section notifications-fix-top" style="background:#31de79">

		<div class="container px-md-5">
				<p class="info-alumno ftco-animate" style="text-align: center;text-transform: uppercase; color: #7c795d; font-family: 'Trocchi', serif; font-size: 25px; font-weight: normal; line-height: 48px; margin: 0;padding: 10px;">
					Historial de  Paquetes suscritos del  Usuario: {{ student.nombre }} {{ student.apellido}}
				</p>
				<button type="button" class="btn btn-primary btn-circle">
				</button> <span style="color: white" class="ftco-animate">Paquete Activo</span><br>
				<button type="button" class="btn btn-danger btn-circle">
				</button>
				<span style="color:white" class="ftco-animate">Paquete Culminado</span>
				<div style="width: 100%;height:20px;"></div>

          {% if paquetes %}
					{% for paquete in paquetes %}
			           <ul class="list-group ftco-animate">
								 {% if paquete.status %}
								 <li class="list-group-item" style="background-color: #3cb371;color:white"> Tipo de paquete: {{ paquete.tipo_de_paquete }}</li>
								 {%else%}
								 <li class="list-group-item" style="background-color: #de2d29;color: white"> Tipo de paquete: {{ paquete.tipo_de_paquete }}</li>
								 {% endif%}
			           <li class="list-group-item"> Fecha de Inscripcion: {{ paquete.fecha_de_inscripcion }}</li>
								 <li class="list-group-item"> Horas consumidas: {{ paquete.horas_consumidas	}} </li>
								 <li class="list-group-item"> Tiempo restante: {{ paquete.horas_restantes }} </li>

								 {% if paquete.status%}
								 <li class="list-group-item">Status: Activo</li>
								 {% else %}
								 <li class="list-group-item" >Status: Culminado</li>
								 {% endif%}
								 <li class="list-group-item mb-5">
									 <a href="{% url 'app:clases' paquete_id=paquete.id %}">
							     <button type="button" class="btn btn-primary">Ver Clases </button>
							     </a>
								 </li>
								{% endfor %}
							</ul>
				{% else %}
				<ul class="list-group" style="padding-bottom: 20px">
							<li class="list-group-item">No hay Paquetes activos para el Usuario: {{ student.nombre }} {{ student.apellido }}</li>
				</ul>
				{% endif %}

		</div>
</section>
</div>

{% endblock content     %}