club/app/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required
app_name ='app'
urlpatterns = [
    path('profile/', views.profile,name='profile'),
    path('historial/',views.historial,name='historial'),
    path('logout/',views.logout_view,name="logout"),
    path('login/',views.LoginView.as_view(),name="login"),
    #path('alumnos/', views.AlumnosListView.as_view(), name='alumnos'),
    path('paquetes/',views.paquetes,name='paquetes'),
    path('formNotification/',views.notificacionPage,name="form_notification"),
    path('notificationsList/',views.notificationsList,name='notificationsList'),
    path('notificationsList/delete_notification/<int:id>',views.deleteNotification,name="borrar_notificacion"),
    path('notificationsList/vista/<int:id>',views.notificacion,name='notificacion'),
    path('notificationsList/delete_by_topic/<str:verb>',views.deleteByTopicNotifications,name='delete_by_topic'),
    path('notificationsList/delete_all_notifications/',views.deleteAllNotification,name='delete_all'),
    path('paquetes/<uuid:paquete_id>/',views.clases,name='clases'),
    path('paquetes/<uuid:paquete_id>/<uuid:clase_id>',views.clase,name='clase'),
    path('events',login_required(views.Eventos.as_view()),name="events"),
    path('change_password/', views.change_password, name='change_password'),
]

club/blog/urls.py
from django.urls import path
from . import views

app_name ='blog'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('testimony/', views.testimony, name='testimony'),
    path('blog/',views.blog.as_view(),name='blog'),
    path('blog/<uuid:id>/',views.postDetail,name="post_detail"),
    path('contact/', views.contact,name="contact"),
    path('services/', views.services, name='services')

]

club/club/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls

admin.site.site_header = "Club de Tareas"
admin.site.site_title = "Club de Tereas Portal"
admin.site.index_title = "Bienvenido al Club de tareas"

urlpatterns = [
    path('', include('app.urls')),
    path('',include('blog.urls')),
    path('admin/', admin.site.urls),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

club/templates/main/base.html
{% load static %}
{% load notifications_tags %}
{% notifications_unread as unread_count %}
<!DOCTYPE html>
<html lang="es">
  <head>
    <title>Club de tareas</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta property="og:type"          content="website" />
    <meta property="og:title"         content="Club de Tareas" />

    {% block meta_tag %}{% endblock%}
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'main/css/fonts.css'%}">
    <link rel="stylesheet" href="{% static 'main/css/open-iconic-bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'main/css/animate.css'%}">
    <link rel="stylesheet" href="{% static 'main/css/search.css'%}">
    <link rel="stylesheet" href="{% static 'main/css/owl.carousel.min.css'%}">
    <link rel="stylesheet" href="{% static 'main/css/owl.theme.default.min.css'%}">
    <link rel="stylesheet" href="{% static 'main/css/magnific-popup.css'%}">
    <link rel="stylesheet" href="{% static 'main/css/aos.css'%}">
    <link rel="stylesheet" href="{% static 'main/css/ionicons.min.css'%}">
    <link rel="stylesheet" href="{% static 'main/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/fix.css' %}">
    <link rel='stylesheet' href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.1.0/fullcalendar.min.css" />
    {% block css_tag %}{%endblock%}
  </head>
  <body  data-target=".site-navbar-target" data-offset="300">

  <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light site-navbar-target" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href="{% url 'blog:home' %}">Club de <span>Tareas</span></a>
	      <button class="navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>

	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav nav ml-auto" style="text-align:center">
	          <li class="nav-item"><a href="{% url 'blog:home' %}" class="nav-link"><span>Home</span></a></li>
	          <li class="nav-item"><a href="{% url 'blog:about' %}"  class="nav-link"><span>Acerca</span></a></li>
	          <li class="nav-item"><a href="{% url 'blog:testimony' %}"  class="nav-link"><span>Testimonios</span></a></li>
	          <li class="nav-item"><a href="{% url 'blog:services' %}" class="nav-link"><span>Servicios</span></a></li>
            <li class="nav-item"><a href="{% url 'blog:blog' %}" class="nav-link"><span>Blog</span></a></li>
            <li class="nav-item"><a href="{% url 'blog:contact' %}" class="nav-link"><span>Contacto</span></a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right" style="text-align: right">

            {% if request.user.is_authenticated %}

            <div class="dropdown" style="padding-right:5px;margin:0;">

                    <a style="border-radius: 10px 10px 10px 10px !important;
                             -moz-border-radius: 10px 10px 10px 10px;
                             -webkit-border-radius: 10px 10px 10px 10px;padding-bottom:0; padding-top:0;padding-left:15px;padding-right:15px;"
                      class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

                      <div style="display: inline-block;position: relative;margin-right:10px;">
                        <i class="fa fa-bell-o" style="font-size: 20px;color: black;"></i>
                        <span class="badge badge-danger" style="border-radius: 50%; position:absolute; top:10%; left:100%; transform: translate(-50%,-50%);">{{ unread_count }}</span>

                      </div>
                          <div class="inset" style="margin-left: 5px;display: inline-block;">
                            <img src="{{ request.user.imagen.url }}">
                          </div>

                    </a>

                    <div class="dropdown-menu ftco-animate" aria-labelledby="dropdownMenuLink" style="margin:0;">
                      <a class="dropdown-item" href="{% url 'app:profile' %}"><span style="padding-right: 5px;"><i class="fa fa-id-card"></i></span><span>Perfil</span></a>
                      <a class="dropdown-item" href="{% url 'app:paquetes' %}"><span style="padding-right: 5px;"><i class="fa fa-window-restore"></i></span><span>Paquetes</span></a>
                      <a class="dropdown-item" href="{% url 'app:historial' %}"><span style="padding-right: 5px;"><i class="fa fa-file"></i></span><span>Historial</span></a>
                      <a class="dropdown-item" href ="{% url 'app:notificationsList' %}">
                        <span style="padding-right: 5px;"><i class="fa fa-comments"></i></span><span>Notificaciones</span>

                          <span class="badge badge-danger">{{ unread_count }}</span>

                      </a>
                      {% if request.user.is_superuser %}
                            <a class="dropdown-item" href="{% url 'admin:index' %}"><span style="padding-right: 5px;"><i class="fa fa-users"></i></span><span>Administración</span></a>
                      {%endif%}
                      <a class="dropdown-item" href="{% url 'app:events' %}">
                        <span style="padding-right: 5px;"><i class="fa fa-calendar"></i></i></span><span>Calendario</span></a>
                      <a class="dropdown-item" href="{% url 'app:change_password' %}"><span style="padding-right: 5px;"><i class="fa fa-key"></i></span><span>Cambiar Password</span></a>
                      <a class="dropdown-item" href="{% url 'app:logout' %}">
                        <span style="padding-right: 5px;"><i class="fa fa-sign-out"></i></span><span>Logout</span></a>
                    </div>
              </div>

            {% else %}
              <li class="nav-item"><a href="{% url 'app:login' %}"  class="nav-link"><span>Login</span></a></li>
            </ul>
          {% endif %}

	      </div>
	    </div>
	  </nav>
    {% if messages %}
      <div class="container" style="position: absolute; top: 80px; left: 5%;z-index: 10000;">
        {% for message in messages  %}
            <div class="alert alert-{{ message.tags }}" id="msg" role="alert" style="width: 100%;">
              <p style="text-align: center;">{{ message }}</p>
            </div>
        {% endfor %}
      </div>

   {% endif %}
    {% block content %}{% endblock %}


    <footer class="ftco-footer ftco-section">
      <div class="container">


        <div class="row mb-5">
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Club de Tareas</h2>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
              <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4 ml-md-4">
              <h2 class="ftco-heading-2">Links</h2>
              <ul class="list-unstyled">
                <li><a href="{% url 'blog:home' %}" ><span class="icon-long-arrow-right mr-2"></span>Home</a></li>
                <li><a href="{% url 'blog:about' %}"><span class="icon-long-arrow-right mr-2"></span>Acerca</a></li>
                <li><a href="{% url 'blog:services' %}"><span class="icon-long-arrow-right mr-2"></span>Servicios</a></li>
                <li><a href="{% url 'blog:blog' %}"><span class="icon-long-arrow-right mr-2"></span>Blog</a></li>
                <li><a href="{% url 'blog:contact' %}"><span class="icon-long-arrow-right mr-2"></span>Contacto</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
             <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Servicios</h2>
              <ul class="list-unstyled">
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Web Design</a></li>
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Web Development</a></li>
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Business Strategy</a></li>
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Data Analysis</a></li>
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Graphic Design</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
            	<h2 class="ftco-heading-2">Have a Questions?</h2>
            	<div class="block-23 mb-3">
	              <ul>
	                <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
	                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
	                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
	              </ul>
	            </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
        Icons made by <a href="https://www.flaticon.com/authors/those-icons" title="Those Icons">Those Icons</a> from <a href="https://www.flaticon.com/" title="Flaticon"> www.flaticon.com</a>
          </div>
        </div>
      </div>
    </footer>



  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>

  <div id="fb-root"></div>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
  <script src="{% static 'main/js/jquery.min.js' %}"></script>
  <script src="{% static 'main/js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'main/js/popper.min.js' %}"></script>
  <script src="{% static 'main/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'main/js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'main/js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'main/js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'main/js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'main/js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'main/js/aos.js'%}"></script>
  <script src="{% static 'main/js/jquery.animateNumber.min.js' %}"></script>
  <script src="{% static 'main/js/scrollax.min.js' %}"></script>
  <!-- <script src="{% static 'app/js/google-map.js' %}"></script> -->
  <script src="{% static 'main/js/main.js' %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
  <script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.1.0/fullcalendar.js'></script>

  {% block script_tag %}{% endblock%}

  <!--<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>-->
  <script async defer crossorigin="anonymous" src="https://connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v5.0"></script>

  </body>
</html>